-- SQLSpec Migration
-- Version: 0001
-- Description: initial migrations for jce
-- Created: 2026-02-01T09:00:03.154718+00:00
-- Author: euri10 <benoit.barthelet@gmail.com>

-- name: migrate-0001-up
-- dialect: sqlite
-- CREATE TABLE keys (
-- 	id INTEGER PRIMARY KEY AUTOINCREMENT,
-- 	keyvalue BLOB NOT NULL,
-- 	fingerprint TEXT NOT NULL,
-- 	keyid TEXT NOT NULL,
-- 	expiration TEXT,
-- 	creation TEXT,
-- 	keytype INTEGER,
--     can_primary_sign INTEGER,
--     oncard TEXT,
--     primary_on_card TEXT
-- );
-- CREATE TABLE subkeys (
--     id INTEGER PRIMARY KEY,
--     key_id INTEGER,
--     fingerprint TEXT NOT NULL,
--     keyid TEXT NOT NULL,
--     expiration TEXT,
--     creation TEXT,
--     keytype TEXT,
--     revoked INTEGER,
--     FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE uidvalues (
--     id INTEGER PRIMARY KEY,
--     value TEXT,
--     revoked INTEGER,
--     key_id INTEGER,
--     FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE uidcerts (
--     id INTEGER PRIMARY KEY,
--     ctype TEXT NOT NULL,
--     creation TEXT,
--     key_id INTEGER,
--     value_id INTEGER,
--     FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE,
--     FOREIGN KEY (value_id) REFERENCES uidvalues (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE uidcertlist (
--     id INTEGER PRIMARY KEY,
--     value TEXT,
--     datatype TEXT,
--     key_id INTEGER,
--     value_id INTEGER,
--     cert_id INTEGER,
--     FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE,
--     FOREIGN KEY (value_id) REFERENCES uidvalues (id) ON DELETE CASCADE,
--     FOREIGN KEY (cert_id) REFERENCES uidcerts (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE uidemails (
--     id INTEGER PRIMARY KEY,
--     value TEXT,
--     key_id INTEGER,
--     value_id INTEGER,
--     FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE,
--     FOREIGN KEY (value_id) REFERENCES uidvalues (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE uidnames (
--     id INTEGER PRIMARY KEY,
--     value TEXT,
--     key_id INTEGER,
--     value_id INTEGER,
--     FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE,
--     FOREIGN KEY (value_id) REFERENCES uidvalues (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE uiduris (
--     id INTEGER PRIMARY KEY,
--     value TEXT,
--     key_id INTEGER,
--     value_id INTEGER,
--     FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE,
--     FOREIGN KEY (value_id) REFERENCES uidvalues (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE dbupgrade (upgradedate TEXT);
--
--dialect: postgres
CREATE TABLE keys (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    keyvalue BYTEA NOT NULL,
    fingerprint TEXT NOT NULL,
    keyid TEXT NOT NULL,
    expiration TEXT,
    creation TEXT,
    keytype INT,
    can_primary_sign INT,
    oncard TEXT,
    primary_on_card TEXT
);

CREATE TABLE subkeys (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    key_id INT,
fingerprint TEXT NOT NULL, keyid
    TEXT NOT NULL,
    expiration TEXT,
    creation TEXT,
    keytype TEXT,
    revoked INT,
    FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE
);

CREATE TABLE uidvalues (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    value TEXT,
    revoked INT,
    key_id INT,
    FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE
);

CREATE TABLE uidcerts (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    ctype TEXT NOT NULL,
    creation TEXT,
    key_id INT,
    value_id INT,
    FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE,
    FOREIGN KEY (value_id) REFERENCES uidvalues (id) ON DELETE CASCADE
);

CREATE TABLE uidcertlist (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    value TEXT,
    datatype TEXT,
    key_id INT,
    value_id INT,
    cert_id INT,
    FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE,
    FOREIGN KEY (value_id) REFERENCES uidvalues (id) ON DELETE CASCADE,
    FOREIGN KEY (cert_id) REFERENCES uidcerts (id) ON DELETE CASCADE
);

CREATE TABLE uidemails (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    value TEXT,
    key_id INT,
    value_id INT,
    FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE,
    FOREIGN KEY (value_id) REFERENCES uidvalues (id) ON DELETE CASCADE
);

CREATE TABLE uidnames (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    value TEXT,
    key_id INT,
    value_id INT,
    FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE,
    FOREIGN KEY (value_id) REFERENCES uidvalues (id) ON DELETE CASCADE
);

CREATE TABLE uiduris (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    value TEXT,
    key_id INT,
    value_id INT,
    FOREIGN KEY (key_id) REFERENCES keys (id) ON DELETE CASCADE,
    FOREIGN KEY (value_id) REFERENCES uidvalues (id) ON DELETE CASCADE
);

-- name: migrate-0001-down
