from typing import Protocol, List, Optional, Union
from datetime import datetime
from johnnycanencrypt.key import Key, Cipher, SignatureType

class KeyStoreProtocol(Protocol):
    def __init__(self, path): ...
    def upgrade_if_required(self): ...
    def update_password(self, key: Key, password: str, newpassword: str) -> Key: ...
    def certify_key(self, key: Union[Key, str], otherkey: Union[Key, str], uids: List[str], sig_type: SignatureType = SignatureType.GenericCertification, password: str = "", oncard: bool = False) -> Key: ...
    def add_key_file_to_db(self, fullpath, uids, fingerprint, keytype, expirationtime=None, creationtime=None, subkeys=[]): ...
    def update_expiry_in_subkeys(self, key: Key, subkeys: List[str], expiration: datetime, password: str) -> Key: ...
    def update_expiry_in_primary(self, key: Key, expiration: datetime, password: str) -> Key: ...
    def add_userid(self, key: Key, userid: str, password: str) -> Key: ...
    def revoke_userid(self, key: Key, userid: str, password: str) -> Key: ...
    def import_key(self, keypath: Union[str, bytes], onplace: bool = False) -> Key: ...
    def details(self): ...
    def get_key(self, fingerprint: str) -> Key: ...
    def get_keys_by_keyid(self, keyid: str): ...
    def get_all_keys(self) -> List[Key]: ...
    def get_keys(self, qvalue: str, qtype: str = "email") -> List[Key]: ...
    def create_key(self, password: str, uids: Optional[Union[List[str], str]] = [], ciphersuite: Cipher = Cipher.RSA4k, creation=None, expiration=None, subkeys_expiration=False, whichkeys=7, can_primary_sign=False, can_primary_expire=False) -> Key: ...
    def delete_key(self, key: Union[str, Key]): ...
    def encrypt(self, keys: Union[List[Union[str, Key]], Union[str, Key]], data: Union[str, bytes], outputfile: Union[str, bytes] = "", armor: bool = True): ...
    def decrypt(self, key: Union[str, Key], data, password: str = ""): ...
    def encrypt_file(self, keys, inputfilepath, outputfilepath, armor: bool = True): ...
    def decrypt_file(self, key: Union[str, Key], encrypted_path, outputfile, password: str = ""): ...
    def sign_detached(self, key: Union[str, Key], data: Union[str, bytes], password): ...
    def verify(self, key: Union[str, Key], data: Union[str, bytes], signature: Optional[str]) -> bool: ...
    def sign_file(self, key: Union[str, Key], filepath: Union[str, bytes], outputpath: Union[str, bytes], password, cleartext: bool = False) -> bool: ...
    def sign_file_detached(self, key: Union[str, Key], filepath: Union[str, bytes], password: str, write: bool = False): ...
    def verify_file_detached(self, key: Union[str, Key], filepath: Union[str, bytes], signature_path): ...
    def verify_file(self, key: Union[str, Key], filepath): ...
    def verify_and_extract_bytes(self, key: Union[str, Key], data: Union[str, bytes]) -> bytes: ...
    def verify_and_extract_file(self, key: Union[str, Key], filepath: Union[str, bytes], output: bytes) -> bool: ...
    def fetch_key_by_fingerprint(self, fingerprint: str): ...
    def fetch_key_by_email(self, email: str): ...
    def sync_smartcard(self) -> str: ...
